### ISSUE TITLE
error forItems undefined

### ISSUE THREAD

**Issue by ding-hub** [vespakoen/modern-extendscript#1]
Trying to run the boilerplate just to check it out I get the following errors so far.

1. had to do a npm install bezier-easing-editor so I could run it
2. aftereffects gives me an error "Function app.project.forItems is undefined"
In DevTools I get
Uncaught (in promise) SyntaxError: Unexpected end of input
on
payload: JSON.parse(payload)

**Comment by vespakoen** [comment]
Hi there!

Thanks for checking out this repository,
I haven't updated this in a long time, and I have made a lot of improvements in the meantime (not in this project though)
I am planning to release a new packager for Adobe Extensions (using ScriptUI or the modern CEP panels) with live reloading capabilities for both.

It will take a while though as I am making a world trip at the moment and "laptop time" is sparse.

Sorry =(
